test

diff --git a/.github/workflows/test.yaml b/.github/workflows/test.yaml
--- a/.github/workflows/test.yaml
+++ b/.github/workflows/test.yaml
@@ -1,10 +1,174 @@
 name: Just for Test
 on:
   workflow_dispatch:
+    inputs:
+      chaos:
+        type: choice
+        required: true
+        description: Chaos experiment to be injected
+        options:
+          - cn-pod-delete-job
+          - mo-io-stress
+          - cn-pod-cpu-hog
+      data:
+        type: choice
+        required: true
+        description: Chaos data to be created
+        options:
+          - create-databases
+
 jobs:
-  Run-Chaos:
+#  deploy_mo_cluster:
+#    name: Deploy
+#    runs-on: amd64-tke-dind
+#    steps:
+#      - uses: actions/checkout@v4
+#        with:
+#          repository: matrixorigin/mo-chaos-driller
+#          path: .
+#          ref: main
+#      - name: Deploy
+#        env:
+#          COS_AK: ${{ secrets.COS_AK }}
+#          COS_SK: ${{ secrets.COS_SK }}
+#        run: |
+#          chmod +x .github/workflows/tke/install-mo.sh
+#          .github/workflows/tke/install-mo.sh
+#        shell: bash
+#      - name: Upload mo cluster artifact
+#        uses: actions/upload-artifact@v3
+#        with:
+#          name: mo-cluster
+#          path: |
+#            name
+#  wait:
+#    name: Wait Until Ready
+#    runs-on: amd64-tke-dind
+#    timeout-minutes: 30
+#    needs:
+#      - deploy_mo_cluster
+#    steps:
+#      - uses: actions/checkout@v4
+#        with:
+#          repository: matrixorigin/mo-chaos-driller
+#          path: .
+#          ref: main
+#      - name: Download mo cluster artifact
+#        uses: actions/download-artifact@v3
+#        with:
+#          name: mo-cluster
+#          path: .
+#      - name: Wait
+#        run: |
+#          chmod +x .github/workflows/tke/wait.sh
+#          .github/workflows/tke/wait.sh
+#        shell: bash
+
+#  prep_data:
+#    name: Prepare CN Data
+#    runs-on: amd64-tke-dind
+#    needs:
+#      - wait
+#    steps:
+#      - uses: actions/checkout@v4
+#        with:
+#          repository: matrixorigin/mo-chaos-driller
+#          path: .
+#          ref: main
+#      - name: Download mo cluster artifact
+#        uses: actions/download-artifact@v3
+#        with:
+#          name: mo-cluster
+#          path: .
+#      - name: Clone Data
+#        run: |
+#          chmod +x .github/workflows/tke/prepare-cn-data.sh
+#          .github/workflows/tke/prepare-cn-data.sh
+#        shell: bash
+
+  chaos:
+    name: Run Chaos
     runs-on: amd64-tke-dind
+#    needs:
+#      - wait
     steps:
+      - uses: actions/checkout@v4
+        with:
+          repository: matrixorigin/mo-chaos-driller
+          path: .
+          ref: main
+#      - name: Download mo cluster artifact
+#        uses: actions/download-artifact@v3
+#        with:
+#          name: mo-cluster
+#          path: .
       - run: |
-          sleep 160
+          set -ex
+          exp=${{ inputs.chaos }}
+          name=uw54hsc8own2jgpg
+          NAMESPACE=chaos-$name
+          kubectl apply -f .github/workflows/tke/$exp.yaml -n $NAMESPACE
+          until kubectl wait --for=condition=ready pod --selector=job-name=$exp --timeout=-1s -n $NAMESPACE
+          do
+              sleep 5
+          done
+          kubectl logs -f job.batch/$exp -n $NAMESPACE
+        shell: bash
         name: Run
+
+  chaos_data:
+    name: Run Chaos Data
+    runs-on: amd64-tke-dind
+#    needs:
+#      - wait
+    steps:
+      - uses: actions/checkout@v4
+        with:
+          repository: matrixorigin/mo-chaos-driller
+          path: .
+          ref: main
+#      - name: Download mo cluster artifact
+#        uses: actions/download-artifact@v3
+#        with:
+#          name: mo-cluster
+#          path: .
+      - run: |
+          set -ex
+          data_scene=${{ inputs.data }}
+          chaos_jobs=${{ inputs.chaos }}
+          name=uw54hsc8own2jgpg
+          NAMESPACE=chaos-$name
+          sed -i "s/\$watch_jobs/$chaos_jobs/g" .github/workflows/tke/$data_scene.yaml
+          kubectl apply -f .github/workflows/tke/$data_scene.yaml -n $NAMESPACE
+          until kubectl wait --for=condition=ready pod --selector=job-name=$data_scene --timeout=-1s -n $NAMESPACE
+          do
+              sleep 5
+          done
+          kubectl logs -f job.batch/$data_scene -n $NAMESPACE
+          # chmod +x .github/workflows/tke/run-chaos-data.sh
+          # .github/workflows/tke/run-chaos-data.sh ${{ inputs.data }} ${{ inputs.chaos }}
+        shell: bash
+        name: Run
+
+
+#  Cleanup:
+#    runs-on: amd64-tke-dind
+#    if: always()
+#    needs:
+#      - tpcc_benchmark_test
+#    steps:
+#      - uses: actions/checkout@v4
+#        with:
+#          repository: matrixorigin/mo-chaos-driller
+#          path: .
+#          ref: main
+#      - name: Download mo cluster artifact
+#        uses: actions/download-artifact@v3
+#        with:
+#          name: mo-cluster
+#          path: .
+#      - name: Cleanup
+#        run: |
+#          chmod +x .github/workflows/tke/clean-mo.sh
+#          .github/workflows/tke/clean-mo.sh
+#        shell: bash
